export const ADD_INSPECTION = "ADD_INSPECTION";
export const ADD_INSPECTIONS = "ADD_INSPECTIONS";
export const UPDATE_INSPECTIION = "UPDATE_INSPECTION";
export const INSPECTIONS_LOADING = "INSPECTIONS_LOADING";
export const INSPECTIONS_FAILED = "INSPECTIONS_FAILED";
export const INSPECTION_SUBMIT = "INSPECTION_SUBMIT";
export const REQUEST_INSPECTION = "REQUEST_INSPECTION";

export const ADD_HOUSE = "ADD_HOUSE";
export const ADD_HOUSES = "ADD_HOUSES";
export const HOUSES_LOADING = "HOUSES_LOADING";
export const HOUSES_FAILED = "HOUSES_FAILED";

export const ADD_BUILDINGTYPES = "ADD_BUILDINGTYPES";
export const BUILDINGTYPES_LOADING = "BUILDINGTYPES_LOADING";
export const BUILDINGTYPES_FAILED = "BUILDINGTYPES_FAILED";

export const ADD_FOUNDATIONS = "ADD_FOUNDATIONS";
export const FOUNDATIONS_LOADING = "FOUNDATIONS_LOADING";
export const FOUNDATIONS_FAILED = "FOUNDATIONS_FAILED";

export const ADD_ELEVATIONS = "ADD_ELEVATIONS";
export const ELEVATIONS_LOADING = "ELEVATIONS_LOADING";
export const ELEVATIONS_FAILED = "ELEVATIONS_FAILED";

export const ADD_ROOFS = "ADD_ROOFS";
export const ROOFS_LOADING = "ROOFS_LOADING";
export const ROOFS_FAILED = "ROOFS_FAILED";

export const ADD_PAVEMENTS = "ADD_PAVEMENTS";
export const PAVEMENTS_LOADING = "PAVEMENTS_LOADING";
export const PAVEMENTS_FAILED = "PAVEMENTS_FAILED";

export const ADD_CEILINGS = "ADD_CEILINGS";
export const CEILINGS_LOADING = "CEILINGS_LOADING";
export const CEILINGS_FAILED = "CEILINGS_FAILED";

export const ADD_CLOSERS = "ADD_CLOSERS";
export const CLOSERS_LOADING = "CLOSERS_LOADING";
export const CLOSERS_FAILED = "CLOSERS_FAILED";

export const ADD_TENURES = "ADD_TENURES";
export const TENURES_LOADING = "TENURES_LOADING";
export const TENURES_FAILED = "TENURES_FAILED";

export const ADD_PROPERTYTYPE = "ADD_PROPERTYTYPE";
export const PROPERTYTYPE_LOADING = "PROPERTYTYPE_LOADING";
export const PROPERTYTYPE_FAILED = "PROPERTYTYPE_FAILED";

export const ADD_PROVINCES = "ADD_PROVINCES";
export const PROVINCES_LOADING = "PROVINCES_LOADING";
export const PROVINCES_FAILED = "PROVINCES_FAILED";

export const ADD_DISTRICTS = "ADD_DISTRICTS";
export const DISTRICTS_LOADING = "DISTRICTS_LOADING";
export const DISTRICTS_FAILED = "DISTRICTS_FAILED";

export const ADD_SECTORS = "ADD_SECTORS";
export const SECTORS_LOADING = "SECTORS_LOADING";
export const SECTORS_FAILED = "SECTORS_FAILED";

export const ADD_CELLS = "ADD_CELLS";
export const CELLS_LOADING = "CELLS_LOADING";
export const CELLS_FAILED = "CELLS_FAILED";

export const ADD_VILLAGES = "ADD_VILLAGES";
export const VILLAGES_LOADING = "VILLAGES_LOADING";
export const VILLAGES_FAILED = "VILLAGES_FAILED";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const CHANGE_ACCOUNT = "CHANGE_ACCOUNT";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
